Exit when unsupported platform

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -159,6 +159,9 @@ case "$(uname -s)" in
           -k /Library/Keychains/System.keychain \
           "${cert_file}"
       ;;
+    *)
+      echo "Unsupported platform.  Cannot install trustRoot"
+      exit 1
 esac
 
 rm -Rf /tmp/traefik-proxy
